version: '{branch}-{build}'
build: off
cache:
  - "%LOCALAPPDATA%\\pip\\Cache"
services:
  - mysql

environment:
  global:
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\tests\\_scripts\\appveyor_with_compiler.cmd"

    MYSQL_PORT: tcp://localhost:3306
    MYSQL_ENV_MYSQL_USER: root
    MYSQL_ENV_MYSQL_PASSWORD: Password12!
    MYSQL_ENV_MYSQL_DATABASE: pyplanet
    MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.7
    MYSQL_PWD: Password12!

  matrix:
    - TOXENV: 'py35-unit-mysql'
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python35
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'

    - TOXENV: 'py35-unit-mysql'
      TOXPYTHON: C:\Python35-x64\python.exe
      PYTHON_HOME: C:\Python35-x64
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'

    - TOXENV: 'py36-unit-mysql'
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'

    - TOXENV: 'py36-unit-mysql'
      TOXPYTHON: C:\Python36-x64\python.exe
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'

init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  # Install Python.
  - python -u tests\_scripts\appveyor_init.py

  # Prepare Database.
  - mysql -u root -e "CREATE DATABASE pyplanet CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

  # Print Versions.
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\easy_install --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'

#before_build

before_test:
  - tests\_scripts\appveyor_config.cmd

test_script:
  - '%WITH_COMPILER% %PYTHON_HOME%\Scripts\tox'

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*

artifacts:
  - path: dist\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
